name: conekt-grasses-snakemake-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohttp=3.8.4=py311h2582759_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - amply=0.1.6=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=25.3.0=pyh71513ae_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bcrypt=3.2.2=py311hd4cff14_1
  - beautifulsoup4=4.12.0=pyha770c72_0
  - biopython=1.81=py311h2582759_0
  - brotli-python=1.1.0=py311hb755f60_1
  - brotlipy=0.7.0=py311hd4cff14_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2024.2.2=hbcca054_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.15.1=py311h409f033_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - coin-or-cbc=2.10.8=h3786ebc_0
  - coin-or-cgl=0.60.6=h6f57e76_2
  - coin-or-clp=1.17.7=hc56784d_2
  - coin-or-osi=0.108.7=h2720bb7_2
  - coin-or-utils=2.11.6=h202d8b1_2
  - coincbc=2.10.8=0_metapackage
  - configargparse=1.7=pyhd8ed1ab_1
  - connection_pool=0.0.3=pyhd3deb0d_0
  - cryptography=39.0.2=py311h9b4c7bb_0
  - datrie=0.8.2=py311hd4cff14_6
  - docutils=0.19=py311h38be061_1
  - dpath=2.1.4=py311h38be061_0
  - ffq=0.3.0=pyhdfd78af_0
  - filelock=3.18.0=pyhd8ed1ab_0
  - frozendict=2.3.6=py311h2582759_1
  - frozenlist=1.3.3=py311hd4cff14_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - google-crc32c=1.5.0=py311h5eee18b_0
  - grpcio=1.52.1=py311hcafe171_1
  - humanfriendly=10.0=py311h38be061_4
  - icu=58.2=hf484d3e_1000
  - idna=3.10=pyhd8ed1ab_1
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - jemalloc=5.3.0=hcb278e6_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jupyter_core=5.3.0=py311h38be061_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libabseil=20230125.0=cxx17_hcb278e6_1
  - libblas=3.9.0=16_linux64_openblas
  - libboost=1.73.0=h28710b8_12
  - libcblas=3.9.0=16_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=12.2.0=h65d4601_19
  - libgrpc=1.52.1=hcf146ea_1
  - libiconv=1.17=h166bdaf_0
  - libjemalloc=5.3.0=hcb278e6_0
  - liblapack=3.9.0=16_linux64_openblas
  - liblapacke=3.9.0=16_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libprotobuf=3.21.12=h3eb15da_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.40.0=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=2.32.1=h7f98852_1000
  - libxml2=2.10.3=hcbfbd50_0
  - libxslt=1.1.37=h873f0b0_0
  - libzlib=1.2.13=h166bdaf_4
  - lxml=4.9.2=py311h14a6109_0
  - markupsafe=2.1.2=py311h2582759_0
  - multidict=6.0.4=py311h2582759_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - numpy=1.24.2=py311h8e6699e_0
  - openssl=3.2.1=hd590300_0
  - pandas=1.5.3=py311h2872171_0
  - pip=25.0.1=pyh8b19718_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - plac=1.4.5=pyhd8ed1ab_0
  - platformdirs=4.3.7=pyh29332c3_0
  - pluggy=1.0.0=py311h38be061_4
  - protobuf=4.21.12=py311hcafe171_0
  - psutil=5.9.4=py311hd4cff14_0
  - pulp=2.7.0=py311h38be061_0
  - pycparser=2.22=pyh29332c3_1
  - pynacl=1.5.0=py311hd4cff14_2
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyrsistent=0.19.3=py311h2582759_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.0=he550d4f_1_cpython
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0=py311hd4cff14_5
  - re2=2023.02.02=hcb278e6_0
  - readline=8.2=h8228510_1
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - reretry=0.11.8=pyhd8ed1ab_1
  - rpds-py=0.22.3=py311h4aa5aa6_0
  - salmon=0.13.1=h86b0361_0
  - setuptools=78.1.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - smart_open=6.3.0=pyhd8ed1ab_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - snakemake-minimal=7.25.0=pyhdfd78af_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - stopit=1.1.2=pyhd8ed1ab_1
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2020.2=h4bd325d_4
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toposort=1.10=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - urllib3=2.3.0=py311h06a4308_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.15.0=py311h2582759_0
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.8.2=py311hd4cff14_0
  - yte=1.5.1=py311h38be061_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
  - pip:
    - backports-tarfile==1.2.0
